[pytest]
# Add the root folder to the module search paths for testing
pythonpath = .
testpaths = tests

# Standard launch flags:
# --cov=<folder_name>           (calculating coverage for this folder)
# --cov-report=term-missing     (shows the line numbers in the console that are NOT covered)
# --cov-fail-under=80
addopts = --cov=clients --cov=models --cov=services --cov=repository --cov-report=term-missing --cov-fail-under=80 -v