from typing import Protocol

from job_analyzer.models.job_dto import JobDTO


class JobRepo(Protocol):

    def get_all_jobs(self) -> list[JobDTO]: ...

    def save_unique_jobs(self, vacancies: list[JobDTO]) -> int: ...

    def get_existing_job_ids(self, hashes: list[str]) -> set[str]:...

    def insert_jobs(self, jobs: list[JobDTO], sync_time) -> int:...

    def touch_jobs(self, hashes: list[str], ts: int) -> int:...

    def mark_jobs_inactive(self, sync_ts: int) -> int:...
